export enum AppRoutes {
  Root = '/',
  Any = '*',
  Login = '/login',
  Registration = '/registration',
  Profile = '/profile',
  Service = '/service',
  Docs = '/docs',
  Contact = '/contact',
  PostsCreate = '/posts/create',
  Posts = '/posts',
  Users = '/users',
  PostDetails = '/posts/:id',
  UserDetails = '/users/:id',
}
